### ISSUE TITLE
gradle not working

### ISSUE THREAD

**Issue by sherifmousa85** [amirisback/sticker-whatsapp#1]
i'm used latest version from android studio and with start edit this app. gradle not working

**Comment by amirisback** [comment]
thanks for information, all issues are fixed. please re-pull this project with latest commit thanks

**Comment by sherifmousa85** [comment]
> thanks for information, all issues are fixed. please re-pull this project with latest commit thanks

sticker-whatsapp still not working with my gradle.
but gradle work with other apps

attached the log error
[idea.log](https://github.com/amirisback/sticker-whatsapp/files/6749405/idea.log)

**Comment by amirisback** [comment]
can you show the red part? better use screenshot

**Comment by sherifmousa85** [comment]
> can you show the red part? better use screenshot

I'm not a programmer, I just modify the name and some other things to use the program. When I use your program, I encounter some problems

**Comment by sherifmousa85** [comment]
For example. after generate app and install Does not open
